//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PathfinderModel", "FK_Information_DepartmentID", "DepartmentInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Information.DepartmentInfo), "Information", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Information.Information), true)]
[assembly: EdmRelationshipAttribute("PathfinderModel", "FK_Information_GenderId", "GendarInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Information.GendarInfo), "Information", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Information.Information), true)]
[assembly: EdmRelationshipAttribute("PathfinderModel", "FK_Information_ReligionID", "Religion", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Information.Religion), "Information", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Information.Information), true)]
[assembly: EdmRelationshipAttribute("PathfinderModel", "FK_Information_SemesterID", "SemesterInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Information.SemesterInfo), "Information", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Information.Information), true)]
[assembly: EdmRelationshipAttribute("PathfinderModel", "FK_Information_ShiftID", "ShiftInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Information.ShiftInfo), "Information", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Information.Information), true)]

#endregion

namespace Information
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PathfinderEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PathfinderEntities object using the connection string found in the 'PathfinderEntities' section of the application configuration file.
        /// </summary>
        public PathfinderEntities() : base("name=PathfinderEntities", "PathfinderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PathfinderEntities object.
        /// </summary>
        public PathfinderEntities(string connectionString) : base(connectionString, "PathfinderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PathfinderEntities object.
        /// </summary>
        public PathfinderEntities(EntityConnection connection) : base(connection, "PathfinderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DepartmentInfo> DepartmentInfoes
        {
            get
            {
                if ((_DepartmentInfoes == null))
                {
                    _DepartmentInfoes = base.CreateObjectSet<DepartmentInfo>("DepartmentInfoes");
                }
                return _DepartmentInfoes;
            }
        }
        private ObjectSet<DepartmentInfo> _DepartmentInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GendarInfo> GendarInfoes
        {
            get
            {
                if ((_GendarInfoes == null))
                {
                    _GendarInfoes = base.CreateObjectSet<GendarInfo>("GendarInfoes");
                }
                return _GendarInfoes;
            }
        }
        private ObjectSet<GendarInfo> _GendarInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Information> Information
        {
            get
            {
                if ((_Information == null))
                {
                    _Information = base.CreateObjectSet<Information>("Information");
                }
                return _Information;
            }
        }
        private ObjectSet<Information> _Information;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Religion> Religions
        {
            get
            {
                if ((_Religions == null))
                {
                    _Religions = base.CreateObjectSet<Religion>("Religions");
                }
                return _Religions;
            }
        }
        private ObjectSet<Religion> _Religions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S_Login> S_Login
        {
            get
            {
                if ((_S_Login == null))
                {
                    _S_Login = base.CreateObjectSet<S_Login>("S_Login");
                }
                return _S_Login;
            }
        }
        private ObjectSet<S_Login> _S_Login;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SemesterInfo> SemesterInfoes
        {
            get
            {
                if ((_SemesterInfoes == null))
                {
                    _SemesterInfoes = base.CreateObjectSet<SemesterInfo>("SemesterInfoes");
                }
                return _SemesterInfoes;
            }
        }
        private ObjectSet<SemesterInfo> _SemesterInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ShiftInfo> ShiftInfoes
        {
            get
            {
                if ((_ShiftInfoes == null))
                {
                    _ShiftInfoes = base.CreateObjectSet<ShiftInfo>("ShiftInfoes");
                }
                return _ShiftInfoes;
            }
        }
        private ObjectSet<ShiftInfo> _ShiftInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DepartmentInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDepartmentInfoes(DepartmentInfo departmentInfo)
        {
            base.AddObject("DepartmentInfoes", departmentInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GendarInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGendarInfoes(GendarInfo gendarInfo)
        {
            base.AddObject("GendarInfoes", gendarInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Information EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInformation(Information information)
        {
            base.AddObject("Information", information);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Religions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReligions(Religion religion)
        {
            base.AddObject("Religions", religion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the S_Login EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToS_Login(S_Login s_Login)
        {
            base.AddObject("S_Login", s_Login);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SemesterInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSemesterInfoes(SemesterInfo semesterInfo)
        {
            base.AddObject("SemesterInfoes", semesterInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ShiftInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShiftInfoes(ShiftInfo shiftInfo)
        {
            base.AddObject("ShiftInfoes", shiftInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<SP_GRIDVIEW_Result> SP_GRIDVIEW()
        {
            return base.ExecuteFunction<SP_GRIDVIEW_Result>("SP_GRIDVIEW");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iID">No Metadata Documentation available.</param>
        /// <param name="dID">No Metadata Documentation available.</param>
        public ObjectResult<SP_DepartmentWiseInformation_Result> SP_DepartmentWiseInformation(Nullable<global::System.Int32> iID, Nullable<global::System.Int32> dID)
        {
            ObjectParameter iIDParameter;
            if (iID.HasValue)
            {
                iIDParameter = new ObjectParameter("IID", iID);
            }
            else
            {
                iIDParameter = new ObjectParameter("IID", typeof(global::System.Int32));
            }
    
            ObjectParameter dIDParameter;
            if (dID.HasValue)
            {
                dIDParameter = new ObjectParameter("DID", dID);
            }
            else
            {
                dIDParameter = new ObjectParameter("DID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<SP_DepartmentWiseInformation_Result>("SP_DepartmentWiseInformation", iIDParameter, dIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<SP_DEPARTMENTINFONAME_Result> SP_DEPARTMENTINFONAME()
        {
            return base.ExecuteFunction<SP_DEPARTMENTINFONAME_Result>("SP_DEPARTMENTINFONAME");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<SP_LOGINUSERNAME_Result> SP_LOGINUSERNAME()
        {
            return base.ExecuteFunction<SP_LOGINUSERNAME_Result>("SP_LOGINUSERNAME");
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PathfinderModel", Name="DepartmentInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DepartmentInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DepartmentInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static DepartmentInfo CreateDepartmentInfo(global::System.Int32 id)
        {
            DepartmentInfo departmentInfo = new DepartmentInfo();
            departmentInfo.Id = id;
            return departmentInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PathfinderModel", "FK_Information_DepartmentID", "Information")]
        public EntityCollection<Information> Information
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Information>("PathfinderModel.FK_Information_DepartmentID", "Information");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Information>("PathfinderModel.FK_Information_DepartmentID", "Information", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PathfinderModel", Name="GendarInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GendarInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GendarInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static GendarInfo CreateGendarInfo(global::System.Int32 id)
        {
            GendarInfo gendarInfo = new GendarInfo();
            gendarInfo.Id = id;
            return gendarInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PathfinderModel", "FK_Information_GenderId", "Information")]
        public EntityCollection<Information> Information
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Information>("PathfinderModel.FK_Information_GenderId", "Information");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Information>("PathfinderModel.FK_Information_GenderId", "Information", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PathfinderModel", Name="Information")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Information : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Information object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Information CreateInformation(global::System.Int32 id)
        {
            Information information = new Information();
            information.Id = id;
            return information;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FatherName
        {
            get
            {
                return _FatherName;
            }
            set
            {
                OnFatherNameChanging(value);
                ReportPropertyChanging("FatherName");
                _FatherName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FatherName");
                OnFatherNameChanged();
            }
        }
        private global::System.String _FatherName;
        partial void OnFatherNameChanging(global::System.String value);
        partial void OnFatherNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Gurden_phone
        {
            get
            {
                return _Gurden_phone;
            }
            set
            {
                OnGurden_phoneChanging(value);
                ReportPropertyChanging("Gurden_phone");
                _Gurden_phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gurden_phone");
                OnGurden_phoneChanged();
            }
        }
        private Nullable<global::System.Int32> _Gurden_phone;
        partial void OnGurden_phoneChanging(Nullable<global::System.Int32> value);
        partial void OnGurden_phoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateofBirth
        {
            get
            {
                return _DateofBirth;
            }
            set
            {
                OnDateofBirthChanging(value);
                ReportPropertyChanging("DateofBirth");
                _DateofBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateofBirth");
                OnDateofBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateofBirth;
        partial void OnDateofBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateofBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nationality
        {
            get
            {
                return _Nationality;
            }
            set
            {
                OnNationalityChanging(value);
                ReportPropertyChanging("Nationality");
                _Nationality = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nationality");
                OnNationalityChanged();
            }
        }
        private global::System.String _Nationality;
        partial void OnNationalityChanging(global::System.String value);
        partial void OnNationalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReligionID
        {
            get
            {
                return _ReligionID;
            }
            set
            {
                OnReligionIDChanging(value);
                ReportPropertyChanging("ReligionID");
                _ReligionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReligionID");
                OnReligionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ReligionID;
        partial void OnReligionIDChanging(Nullable<global::System.Int32> value);
        partial void OnReligionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SemesterID
        {
            get
            {
                return _SemesterID;
            }
            set
            {
                OnSemesterIDChanging(value);
                ReportPropertyChanging("SemesterID");
                _SemesterID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SemesterID");
                OnSemesterIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SemesterID;
        partial void OnSemesterIDChanging(Nullable<global::System.Int32> value);
        partial void OnSemesterIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ShiftId
        {
            get
            {
                return _ShiftId;
            }
            set
            {
                OnShiftIdChanging(value);
                ReportPropertyChanging("ShiftId");
                _ShiftId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShiftId");
                OnShiftIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ShiftId;
        partial void OnShiftIdChanging(Nullable<global::System.Int32> value);
        partial void OnShiftIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GenderId
        {
            get
            {
                return _GenderId;
            }
            set
            {
                OnGenderIdChanging(value);
                ReportPropertyChanging("GenderId");
                _GenderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenderId");
                OnGenderIdChanged();
            }
        }
        private Nullable<global::System.Int32> _GenderId;
        partial void OnGenderIdChanging(Nullable<global::System.Int32> value);
        partial void OnGenderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DepartmentId
        {
            get
            {
                return _DepartmentId;
            }
            set
            {
                OnDepartmentIdChanging(value);
                ReportPropertyChanging("DepartmentId");
                _DepartmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentId");
                OnDepartmentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DepartmentId;
        partial void OnDepartmentIdChanging(Nullable<global::System.Int32> value);
        partial void OnDepartmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private Nullable<global::System.Int32> _Phone;
        partial void OnPhoneChanging(Nullable<global::System.Int32> value);
        partial void OnPhoneChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PathfinderModel", "FK_Information_DepartmentID", "DepartmentInfo")]
        public DepartmentInfo DepartmentInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DepartmentInfo>("PathfinderModel.FK_Information_DepartmentID", "DepartmentInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DepartmentInfo>("PathfinderModel.FK_Information_DepartmentID", "DepartmentInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DepartmentInfo> DepartmentInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DepartmentInfo>("PathfinderModel.FK_Information_DepartmentID", "DepartmentInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DepartmentInfo>("PathfinderModel.FK_Information_DepartmentID", "DepartmentInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PathfinderModel", "FK_Information_GenderId", "GendarInfo")]
        public GendarInfo GendarInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GendarInfo>("PathfinderModel.FK_Information_GenderId", "GendarInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GendarInfo>("PathfinderModel.FK_Information_GenderId", "GendarInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GendarInfo> GendarInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GendarInfo>("PathfinderModel.FK_Information_GenderId", "GendarInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GendarInfo>("PathfinderModel.FK_Information_GenderId", "GendarInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PathfinderModel", "FK_Information_ReligionID", "Religion")]
        public Religion Religion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Religion>("PathfinderModel.FK_Information_ReligionID", "Religion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Religion>("PathfinderModel.FK_Information_ReligionID", "Religion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Religion> ReligionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Religion>("PathfinderModel.FK_Information_ReligionID", "Religion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Religion>("PathfinderModel.FK_Information_ReligionID", "Religion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PathfinderModel", "FK_Information_SemesterID", "SemesterInfo")]
        public SemesterInfo SemesterInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SemesterInfo>("PathfinderModel.FK_Information_SemesterID", "SemesterInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SemesterInfo>("PathfinderModel.FK_Information_SemesterID", "SemesterInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SemesterInfo> SemesterInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SemesterInfo>("PathfinderModel.FK_Information_SemesterID", "SemesterInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SemesterInfo>("PathfinderModel.FK_Information_SemesterID", "SemesterInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PathfinderModel", "FK_Information_ShiftID", "ShiftInfo")]
        public ShiftInfo ShiftInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShiftInfo>("PathfinderModel.FK_Information_ShiftID", "ShiftInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShiftInfo>("PathfinderModel.FK_Information_ShiftID", "ShiftInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ShiftInfo> ShiftInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShiftInfo>("PathfinderModel.FK_Information_ShiftID", "ShiftInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ShiftInfo>("PathfinderModel.FK_Information_ShiftID", "ShiftInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PathfinderModel", Name="Religion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Religion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Religion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Religion CreateReligion(global::System.Int32 id)
        {
            Religion religion = new Religion();
            religion.Id = id;
            return religion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PathfinderModel", "FK_Information_ReligionID", "Information")]
        public EntityCollection<Information> Information
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Information>("PathfinderModel.FK_Information_ReligionID", "Information");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Information>("PathfinderModel.FK_Information_ReligionID", "Information", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PathfinderModel", Name="S_Login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S_Login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S_Login object.
        /// </summary>
        /// <param name="userName">Initial value of the UserName property.</param>
        public static S_Login CreateS_Login(global::System.String userName)
        {
            S_Login s_Login = new S_Login();
            s_Login.UserName = userName;
            return s_Login;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PathfinderModel", Name="SemesterInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SemesterInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SemesterInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static SemesterInfo CreateSemesterInfo(global::System.Int32 id)
        {
            SemesterInfo semesterInfo = new SemesterInfo();
            semesterInfo.Id = id;
            return semesterInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PathfinderModel", "FK_Information_SemesterID", "Information")]
        public EntityCollection<Information> Information
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Information>("PathfinderModel.FK_Information_SemesterID", "Information");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Information>("PathfinderModel.FK_Information_SemesterID", "Information", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PathfinderModel", Name="ShiftInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ShiftInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShiftInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static ShiftInfo CreateShiftInfo(global::System.Int32 id)
        {
            ShiftInfo shiftInfo = new ShiftInfo();
            shiftInfo.Id = id;
            return shiftInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PathfinderModel", "FK_Information_ShiftID", "Information")]
        public EntityCollection<Information> Information
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Information>("PathfinderModel.FK_Information_ShiftID", "Information");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Information>("PathfinderModel.FK_Information_ShiftID", "Information", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PathfinderModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="PathfinderModel", Name="SP_DEPARTMENTINFONAME_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_DEPARTMENTINFONAME_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="PathfinderModel", Name="SP_DepartmentWiseInformation_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_DepartmentWiseInformation_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SP_DepartmentWiseInformation_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="gemder">Initial value of the Gemder property.</param>
        /// <param name="semester">Initial value of the Semester property.</param>
        /// <param name="shift">Initial value of the Shift property.</param>
        public static SP_DepartmentWiseInformation_Result CreateSP_DepartmentWiseInformation_Result(global::System.Int32 id, global::System.String gemder, global::System.String semester, global::System.String shift)
        {
            SP_DepartmentWiseInformation_Result sP_DepartmentWiseInformation_Result = new SP_DepartmentWiseInformation_Result();
            sP_DepartmentWiseInformation_Result.Id = id;
            sP_DepartmentWiseInformation_Result.Gemder = gemder;
            sP_DepartmentWiseInformation_Result.Semester = semester;
            sP_DepartmentWiseInformation_Result.Shift = shift;
            return sP_DepartmentWiseInformation_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateofBirth
        {
            get
            {
                return _DateofBirth;
            }
            set
            {
                OnDateofBirthChanging(value);
                ReportPropertyChanging("DateofBirth");
                _DateofBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateofBirth");
                OnDateofBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateofBirth;
        partial void OnDateofBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateofBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nationality
        {
            get
            {
                return _Nationality;
            }
            set
            {
                OnNationalityChanging(value);
                ReportPropertyChanging("Nationality");
                _Nationality = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nationality");
                OnNationalityChanged();
            }
        }
        private global::System.String _Nationality;
        partial void OnNationalityChanging(global::System.String value);
        partial void OnNationalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gemder
        {
            get
            {
                return _Gemder;
            }
            set
            {
                OnGemderChanging(value);
                ReportPropertyChanging("Gemder");
                _Gemder = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gemder");
                OnGemderChanged();
            }
        }
        private global::System.String _Gemder;
        partial void OnGemderChanging(global::System.String value);
        partial void OnGemderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Semester
        {
            get
            {
                return _Semester;
            }
            set
            {
                OnSemesterChanging(value);
                ReportPropertyChanging("Semester");
                _Semester = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Semester");
                OnSemesterChanged();
            }
        }
        private global::System.String _Semester;
        partial void OnSemesterChanging(global::System.String value);
        partial void OnSemesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Shift
        {
            get
            {
                return _Shift;
            }
            set
            {
                OnShiftChanging(value);
                ReportPropertyChanging("Shift");
                _Shift = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Shift");
                OnShiftChanged();
            }
        }
        private global::System.String _Shift;
        partial void OnShiftChanging(global::System.String value);
        partial void OnShiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private Nullable<global::System.Int32> _Phone;
        partial void OnPhoneChanging(Nullable<global::System.Int32> value);
        partial void OnPhoneChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="PathfinderModel", Name="SP_GRIDVIEW_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_GRIDVIEW_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SP_GRIDVIEW_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="shift">Initial value of the Shift property.</param>
        public static SP_GRIDVIEW_Result CreateSP_GRIDVIEW_Result(global::System.Int32 id, global::System.String gender, global::System.String shift)
        {
            SP_GRIDVIEW_Result sP_GRIDVIEW_Result = new SP_GRIDVIEW_Result();
            sP_GRIDVIEW_Result.Id = id;
            sP_GRIDVIEW_Result.Gender = gender;
            sP_GRIDVIEW_Result.Shift = shift;
            return sP_GRIDVIEW_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateofBirth
        {
            get
            {
                return _DateofBirth;
            }
            set
            {
                OnDateofBirthChanging(value);
                ReportPropertyChanging("DateofBirth");
                _DateofBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateofBirth");
                OnDateofBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateofBirth;
        partial void OnDateofBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateofBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Shift
        {
            get
            {
                return _Shift;
            }
            set
            {
                OnShiftChanging(value);
                ReportPropertyChanging("Shift");
                _Shift = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Shift");
                OnShiftChanged();
            }
        }
        private global::System.String _Shift;
        partial void OnShiftChanging(global::System.String value);
        partial void OnShiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DepartmentId
        {
            get
            {
                return _DepartmentId;
            }
            set
            {
                OnDepartmentIdChanging(value);
                ReportPropertyChanging("DepartmentId");
                _DepartmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentId");
                OnDepartmentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DepartmentId;
        partial void OnDepartmentIdChanging(Nullable<global::System.Int32> value);
        partial void OnDepartmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GenderId
        {
            get
            {
                return _GenderId;
            }
            set
            {
                OnGenderIdChanging(value);
                ReportPropertyChanging("GenderId");
                _GenderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenderId");
                OnGenderIdChanged();
            }
        }
        private Nullable<global::System.Int32> _GenderId;
        partial void OnGenderIdChanging(Nullable<global::System.Int32> value);
        partial void OnGenderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReligionID
        {
            get
            {
                return _ReligionID;
            }
            set
            {
                OnReligionIDChanging(value);
                ReportPropertyChanging("ReligionID");
                _ReligionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReligionID");
                OnReligionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ReligionID;
        partial void OnReligionIDChanging(Nullable<global::System.Int32> value);
        partial void OnReligionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nationality
        {
            get
            {
                return _Nationality;
            }
            set
            {
                OnNationalityChanging(value);
                ReportPropertyChanging("Nationality");
                _Nationality = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nationality");
                OnNationalityChanged();
            }
        }
        private global::System.String _Nationality;
        partial void OnNationalityChanging(global::System.String value);
        partial void OnNationalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private Nullable<global::System.Int32> _Phone;
        partial void OnPhoneChanging(Nullable<global::System.Int32> value);
        partial void OnPhoneChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="PathfinderModel", Name="SP_LOGINUSERNAME_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_LOGINUSERNAME_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SP_LOGINUSERNAME_Result object.
        /// </summary>
        /// <param name="userName">Initial value of the UserName property.</param>
        public static SP_LOGINUSERNAME_Result CreateSP_LOGINUSERNAME_Result(global::System.String userName)
        {
            SP_LOGINUSERNAME_Result sP_LOGINUSERNAME_Result = new SP_LOGINUSERNAME_Result();
            sP_LOGINUSERNAME_Result.UserName = userName;
            return sP_LOGINUSERNAME_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion

    }

    #endregion

    
}
